### ISSUE TITLE
Shiny!

### ISSUE THREAD

**Issue by kach** [bojidar-bg/nearley-grammar#1]
Just wanted to say how cool this is. Is it more of a WIP or can I put a link in nearley's README for others to find? :-)

**Comment by bojidar-bg** [comment]
@Hardmath123 Well, those regexes fail miserably on some test cases, but otherwise it is good (also, won't ever support `@postprocess`, methinks). E.g. I'm fine with linking it in README's

**Comment by kach** [comment]
Cool, I'll do that.
