### ISSUE TITLE
Strings are detected inside comments

### ISSUE THREAD

**Issue by YarnSphere** [bojidar-bg/nearley-grammar#2]
A preview of the `calculator` example:

![screenshot from 2016-03-22 20-52-16](https://cloud.githubusercontent.com/assets/8314616/13967618/0e88eec8-f070-11e5-9922-5e691c73f1e5.png)

The cursor shows the beginning of the "string".

**Comment by whitten** [comment]
Could you share the grammar you are using?
specifically, the part of the grammar related to comments and strings.

**Comment by YarnSphere** [comment]
https://github.com/Hardmath123/nearley/blob/master/examples/calculator/arithmetic.ne

**Comment by trevorr** [comment]
I see this too. My PR #3 fixes this by adding support for comments and character classes.

**Comment by bates64** [comment]
@bojidar-bg This is fixed by #3 (merged), but it hasn't been publish to `apm` yet- please do.

**Comment by bojidar-bg** [comment]
Yeah, will do in an hour (I hope..).

**Comment by bojidar-bg** [comment]
Ok, I think it happened, but since I messed things up with git a bit, can you confirm everything is fine?

**Comment by bojidar-bg** [comment]
Seems to work fine here, closing.
